# Generated by Django 3.2.18 on 2023-04-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230325_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_fingerprint_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_fingerprint_enrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_fingerprint_need_re_enrolled',
            field=models.BooleanField(default=True),
        ),
    ]
