# Generated by Django 3.2.18 on 2023-05-07 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_alter_semester_year'),
        ('users', '0004_auto_20230430_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.semester'),
        ),
    ]
