# Generated by Django 3.2.18 on 2023-05-07 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_alter_semester_year'),
        ('class_room', '0001_initial'),
        ('feedback_to_professors', '0002_auto_20230326_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktoprofessors',
            name='semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='metadata.semester'),
        ),
        migrations.AlterField(
            model_name='feedbacktoprofessors',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='class_room.subject'),
        ),
    ]
