# Generated by Django 4.1.7 on 2023-02-26 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackItems',
            fields=[
                ('feedback_items_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('*', '1'), ('**', '2'), ('***', '3'), ('****', '4'), ('*****', '5')], default='*', max_length=5)),
                ('message', models.TextField()),
                ('feedback_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbackitems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
