# Generated by Django 3.2.18 on 2023-03-25 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackItems',
            fields=[
                ('feedback_items_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('*', '1'), ('**', '2'), ('***', '3'), ('****', '4'), ('*****', '5')], default='*', max_length=5)),
                ('message', models.TextField()),
                ('feedback_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbackitems')),
            ],
        ),
    ]
