# Generated by Django 4.1.7 on 2023-02-26 10:07

from django.db import migrations, models
import django.db.models.deletion

from metadata.migrations import create_table_data


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.university')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=200, unique=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.course')),
            ],
        ),
        migrations.RunPython(create_table_data),
    ]
